logging:
  level:
    root: INFO

server:
  error:
    include-stacktrace: always

spring:
  config:
    activate:
      on-profile: dev

  security:
    user:
      name: user
      password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/template_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # default_schema: template_schema