logging:
  level:
    root: WARN

spring:
  config:
    activate:
      on-profile: prod

  security:
    user:
      name: admin
      password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false