logging:
  level:
    root: INFO
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

server:
  error:
    include-stacktrace: always

spring:
  config:
    activate:
      on-profile: dev

  security:
#    user:
#      name: user
#      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/master

#  datasource:
#    url: jdbc:postgresql://localhost:5432/app_db
#    username: postgres
#    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # default_schema: template_schema

  docker:
    compose:
      enabled: false
      file: docker-compose.yml