create table if not exists users
(
    age        integer,
    created_at timestamp(6),
    id         bigint generated by default as identity,
    updated_at timestamp(6),
    created_by varchar(255),
    updated_by varchar(255),
    username   varchar(255) not null unique,
    primary key (id)
)
